@echo off
setlocal

echo.
echo === KiCad Project Cleaning Script (V2) ===
echo.
echo This script will delete auto-generated files and folders.
echo.

:: --- 1. Delete KiCad Cache Files and Local Settings ---
:: Deletes the footprint cache file (regenerated by KiCad)
del /f /s /q "fp-info-cache" 2>nul
:: Deletes the local project preferences file (user-specific settings)
del /f /s /q "*.kicad_prl" 2>nul
:: Deletes netlist files (generated from schematic)
del /f /s /q "*.net" 2>nul

echo Deleted cache and local settings.

:: --- 2. Delete Temporary and Backup Files ---
:: Deletes common temporary files
del /f /s /q "*.tmp" 2>nul
:: Deletes common backup files
del /f /s /q "*.bak" 2>nul
:: Deletes files ending in '~' (common Linux/Git backup markers)
del /f /s /q "*~" 2>nul
:: Deletes auto-save files
del /f /s /q "*_autosave-*" 2>nul
:: Deletes lock files (can sometimes persist after a crash)
del /f /s /q "*.lck" 2>nul

echo Deleted temporary and backup files.

:: --- 3. Delete Backup Folders ---
:: Use FOR /D to reliably delete folders matching *-backups
FOR /D %%i IN (*-backups) DO (
    rd /s /q "%%i" 2>nul
)
echo Deleted backup folders.

:: --- 4. Delete Backup Folders ---
:: Deletes the 'out' folder (common output directory for builds)
rd /s /q out 2>nul

echo Deleted out folders.

endlocal